models: 
  - name: Store Performance Mart
    description: This store performance mart model is created to help managers compare monthly store performance across regions in order to identify and replicate best-performing stores.
    